### ISSUE TITLE
[BUG] - kader rond link binnen een vl-alert wordt afgekapt

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-alert#107]
**Omschrijf het probleem**
Bij het klikken van een link die zich in een vl-alert bevindt, wordt de kader niet helemaal getoond.

**Hoe te reproduceren**
Dit is zichtbaar op demo pagina van vl-alert, ook bij Webuniversum
```
<vl-alert id="alert-closable" data-vl-icon="warning" data-vl-title="Opgelet!" data-vl-closable>
    <p>U heeft geen rechten om deze actie uit te voeren. <a href="#">Vraag rechten aan</a>.</p>
</vl-alert>
```
![image](https://user-images.githubusercontent.com/29454303/106245431-b920db80-620c-11eb-8a23-803f5cb6c660.png)

Hier een andere variant waarbij de demo code licht werd gewijzigd:
```
<vl-alert id="alert" data-vl-icon="warning" data-vl-title="Opgelet!">
  <p>U heeft geen rechten om deze actie uit te voeren.</p>
  <p><a href="#">Vraag rechten aan</a>.</p>
</vl-alert>
```
<img width="791" alt="image" src="https://user-images.githubusercontent.com/29454303/106245542-e66d8980-620c-11eb-828b-4080c43f6377.png">

**Gewenst gedrag**
Correcte weergave link:
<img width="160" alt="image" src="https://user-images.githubusercontent.com/29454303/106245788-58de6980-620d-11eb-81bc-149eb145b157.png">

**Screenshots**
Hier een screenshot van het probleem in onze applicatie:

<img width="985" alt="image" src="https://user-images.githubusercontent.com/29454303/106245672-259bda80-620d-11eb-9588-3c24df28f0ca.png">

**Omgeving (gelieve aan te vullen):**
 - Browser any
 - Versie component 4.0.1

**Comment by coemans** [comment]
Dit issue zal opgelost zijn bij een volgende update.

**Comment by kevcraey** [comment]
ticket aangemaakt
